
[window]

opacity = 0.9

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark" # "Dark"

[font]

normal.family = "Meslo LGM Nerd Font"
bold.family = "Meslo LGM Nerd Font"
italic.family = "Meslo LGM Nerd Font"
bold_italic.family = "Meslo LGM Nerd Font"

size = 9.5

[general]
import = ["~/.config/alacritty/themes/gruvbox-material-medium-dark.toml"]
